function psfwrite(psffilename,M,pairlist,sysname)
% psfwrite(psffilename,M,pairlist,sysname)
%
% write molecular properties and bond information to psf file format, for
% visualization with vmd (only pairwise bonds are included).
%
% psffilename   filename to write to (overwritten)
% M             pdb structure
% pairlist      matrix of atom numbers to draw bonds between, one pair per
%               row.
% sysname       name string for system (no format specs)
% M.L. 2012-11-02

fid=fopen(psffilename,'w'); % open and overwrite

% PSF header
fprintf(fid,'PSF\n');
fprintf(fid,'\n');
fprintf(fid,'       2 !NTITLE\n');
fprintf(fid,' REMARKS generated by matlab script (by M.L.)\n');
fprintf(fid,' REMARKS system name : %s \n',sysname);

% atom records
fprintf(fid,'%8d !NATOM\n',length(M.Model.Atom));
for k=1:length(M.Model.Atom)
    %The fields in the atom section are 
    % atom ID, 
    atomID=k;
    % segment name, no spaces
    segmentName=M.Model.Atom(k).segID;
    segmentName=segmentName(~segmentName==' ');
    % residue ID,
    residueID=M.Model.Atom(k).resSeq;
    %residue name,
    residueName=M.Model.Atom(k).resName;
    %atom name,
    atomName=M.Model.Atom(k).AtomName;
    %atom type,
    atomType=[M.Model.Atom(k).AtomNameStruct.chemSymbol ...
              M.Model.Atom(k).AtomNameStruct.remoteInd];
                  %M.Model.Atom(k).AtomNameStruct.branch];
    %charge
    charge=0;
    %mass, 
    mass=1;
    %and an unused 0.
    fprintf(fid,'%8d%1s%6d%7s%5s%4s %12.6f %13.3f%12d\n',...
        atomID,segmentName,residueID,residueName,atomName,atomType,charge,mass,0);
                             
end
fprintf(fid,'\n');
% bonds 
fprintf(fid,'%8d !NBOND\n',size(pairlist,1));
psfbonds=reshape(pairlist',1,prod(size(pairlist)));
fprintf(fid,'%8d%8d%8d%8d%8d%8d%8d%8d\n',psfbonds);   
fprintf(fid,'\n');
% other sections (empty)
fprintf(fid,'       0 !NTHETA: angles\n');
fprintf(fid,'       0 !NPHI: dihedrals\n');
fprintf(fid,'       0 !NIMPHI: impropers\n');
fprintf(fid,'       0 !NDON: donors\n');


